name: Deploy CDK

on:
  push:
    branches:
      - main

jobs:
  cdk-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Check out code
        uses: actions/checkout@v3

      # Step 2: Configure AWS Credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      # Step 3: Install esbuild globally
      - name: Install esbuild globally
        run: npm install -g esbuild

      # Step 4: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 5: Deploy via CDK (npm run deploy)
      - name: Deploy CDK
        run: npm run deploy
        env:
          GEMINI_CREDENTIALS: ${{ secrets.GEMINI_CREDENTIALS }}
          BLUESKY_CREDENTIALS: ${{ secrets.BLUESKY_CREDENTIALS }}
          SLACK_URL: ${{ secrets.SLACK_URL }}
